spring.application.name=CodePhoenix-AI

server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/codephoenix
spring.datasource.username=postgres
spring.datasource.password=au@123456

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Hikari connection startup behavior
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# File Upload
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Upload Directory
file.upload-dir=uploads/projects

# JWT
jwt.secret=CodePhoenixSecretKeyForJWTAuthentication2026CodePhoenix
jwt.expiration=86400000

# Swagger


# Gemini
gemini.api.key=${GEMINI_API_KEY:}

# Logging
logging.level.org.springframework.security=DEBUG